alarm_active:
- true
- true
- true
- true
- true
- true
- true
- true
alarm_threshold_ask:
- 3
- 3
- 3
- 3
- 3
- 3
- 3
- 3
alarm_threshold_bid:
- 6
- 6
- 6
- 6
- 6
- 6
- 6
- 6
conf_thresh: 80
debug: true
interval: 1
logfile: app.log
rois:
  left:
  - 627
  - 337
  - 676
  - 606
  right:
  - 944
  - 337
  - 1017
  - 644
screen_id: 1
time_periods:
- 10
- 20
- 30
- 60
- 300
- 1200
- 3600
