alarm_active:
- true
- true
- true
- true
- true
- true
- true
- true
alarm_threshold_ask:
- 3000
- 4
- 2
- 1
- 1
- 1
- 1
- 5
alarm_threshold_bid:
- 8000
- 2
- 2
- 2
- 2
- 2
- 2
- 2
conf_thresh: 80
debug: true
interval: 1
logfile: app.log
rois:
  left:
  - 385
  - 127
  - 433
  - 214
  right:
  - 444
  - 127
  - 521
  - 220
screen_id: 1
time_periods:
- 10
- 20
- 30
- 60
- 300
- 1200
- 3600
