conf_thresh: 80
debug: true
interval: 1
logfile: app.log
rois:
  left:
  - 991
  - 239
  - 1053
  - 841
  right:
  - 1338
  - 239
  - 1401
  - 848
time_periods:
- 10
- 20
- 30
- 60
- 300
- 1200
- 3600
